from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .common import GEN_SRC, GEN_TEX, ensure_dirs, normalize_name
from .sources import chapter_source


AUTHOR = {
    "schulte": "Christian Schulte",
    "tack": "Guido Tack",
    "lagerkvist": "Mikael Lagerkvist",
}


@dataclass
class Block:
    name: str
    text: str


def _quote_tex(s: str) -> str:
    s = s.replace("\\", r"\(\backslash\)")
    for c in "$#&_%{}":
        s = s.replace(c, f"\\{c}")
    s = s.replace("~", r"\textasciitilde{}")
    s = s.replace("<", r"\symbol{60}")
    s = s.replace(">", r"\symbol{62}")
    s = s.replace("...", r"\litanon")
    s = s.replace("^", r"\^{}")
    return s


def _inline_cpp_to_tex(line: str) -> str:
    while True:
        m = re.search(r"\\\?(.+?)\\\?", line)
        if not m:
            return line
        content = _quote_tex(m.group(1)).replace(" ", r"\lits{}")
        repl = "\\CppInline{" + content + "}"
        line = line[: m.start()] + repl + line[m.end() :]


def _output_block(blockref: str, blockname: str, code: str, with_label: bool, small: bool, download: str | None) -> str:
    lines = code.splitlines()
    ws = 0
    if lines:
        ws = len(lines[0]) - len(lines[0].lstrip())
    out: list[str] = []
    out.append("\\smalllitcodeblock{%" if small else "\\litcodeblock{%")
    if with_label:
        if download:
            out.append(f"\\noindent\\litfile{{lit:{blockref}}}{{{blockname}}}{{{download}}}\\\\")
        else:
            out.append(f"\\noindent\\litlabel{{lit:{blockref}}}{{{blockname}}}\\\\")
    else:
        out.append("\\noindent")
    for i, line in enumerate(lines):
        if i:
            out.append(r"\\")
        l = line[ws:] if ws <= len(line) else line
        if "\\litref" in l:
            out.append(r"\lits\lits{}" + l.replace(" ", r"\lits{}"))
        else:
            out.append(r"\lits\lits{}" + _quote_tex(l).replace(" ", r"\lits{}"))
    out.append("}")
    return "\n".join(out) + "\n"


def _resolve_block_key(key: str, blocks: dict[str, str]) -> str | None:
    if key in blocks:
        return key
    # Accept aliased block ids that include repeated prefixes.
    for k in blocks:
        if k.endswith(":" + key):
            return k
    for k in blocks:
        if key.endswith(":" + k):
            return k
    return None


def process_literate_file(src: Path, dst: Path, year: str, emit_cpp: bool = True) -> list[str]:
    ensure_dirs()
    line_no = 0
    document: list[str] = []
    blocks: dict[str, str] = {}
    block_names: dict[str, str] = {}
    download: dict[str, str] = {}

    in_litcode = False
    in_texonly = False
    cur_code = ""
    cur_block = ""
    stack: list[str] = []
    code_file = None
    code_path: Path | None = None

    with src.open(encoding="utf-8") as f:
        for raw in f:
            line_no += 1
            l = raw.rstrip("\n")

            m = re.match(r"\\begin\{litcode\}\[texonly\]\{(.*)\}", l)
            if m:
                if in_litcode:
                    raise RuntimeError(f"Nested litcode at {src}:{line_no}")
                in_litcode = True
                cur_code = m.group(1)
                code_file = None
                continue

            m = re.match(r"\\begin\{litcode\}\{(.*)\}\{(.*)\}", l)
            if m:
                if in_litcode:
                    raise RuntimeError(f"Nested litcode at {src}:{line_no}")
                in_litcode = True
                cur_code = m.group(1)
                filename = normalize_name(cur_code)
                if "." not in filename:
                    filename += ".cpp"
                download[cur_code] = filename
                if emit_cpp:
                    code_path = GEN_SRC / filename
                    code_path.parent.mkdir(parents=True, exist_ok=True)
                    code_file = code_path.open("w", encoding="utf-8")
                    code_file.write("/*\n * Auto-generated by mpg extract\n */\n\n")
                continue

            if l == r"\end{litcode}":
                if not in_litcode:
                    raise RuntimeError(f"Unmatched end litcode at {src}:{line_no}")
                in_litcode = False
                if code_file:
                    code_file.close()
                blocks[cur_code] = cur_block
                block_names[cur_code] = cur_code
                cur_block = ""
                stack.clear()
                in_texonly = False
                continue

            if not in_litcode:
                document.append(_inline_cpp_to_tex(l) + "\n")
                continue

            m = re.match(r"\s*\\begin\{litblock\}\{(.*)\}", l)
            if m:
                name = m.group(1)
                if name == "texonly":
                    in_texonly = True
                    stack.append(name)
                    continue
                stack.append(cur_block)
                stack.append(name)
                cur_block = ""
                comment = name.split(":")[-1]
                if code_file and name not in ("anonymous", "ignore") and not in_texonly:
                    code_file.write(f"// {comment}\n")
                continue

            m = re.match(r"(\s*)\\end\{litblock\}", l)
            if m:
                ws = m.group(1)
                n = stack.pop() if stack else ""
                t = n.split(":")[-1] if n else ""
                if n == "texonly":
                    in_texonly = False
                    continue
                blocks[f"{cur_code}:{n}"] = cur_block
                block_names[f"{cur_code}:{n}"] = t
                prev = stack.pop() if stack else ""
                cur_block = prev
                if n == "anonymous":
                    cur_block += ws + "...\n"
                elif n != "ignore":
                    cur_block += ws + f"\\litref{{lit:{cur_code}:{n}}}{{{t}}}\n"
                continue

            if l.strip() == "/*":
                stack.append(cur_block)
                stack.append("ignore")
                cur_block = l + "\n"
                if code_file and not in_texonly:
                    code_file.write(l + "\n")
                continue

            if l.strip() == "*/":
                n = stack.pop() if stack else ""
                if n != "ignore":
                    raise RuntimeError(f"Block inside multiline comment at {src}:{line_no}")
                cur_block = stack.pop() if stack else ""
                if code_file and not in_texonly:
                    code_file.write(l + "\n")
                continue

            cur_block += l + "\n"
            if code_file and not in_texonly:
                code_file.write(l + "\n")

    out: list[str] = []
    for line in document:
        m = re.search(r"\\insertlitcode\[direct\]\{(.*)\}", line)
        if m:
            k = _resolve_block_key(m.group(1), blocks)
            if k is None:
                out.append(line)
            else:
                out.append(_output_block(k, block_names[k], blocks[k], False, False, download.get(k)))
            continue
        m = re.search(r"\\insertlitcode\{(.*)\}", line)
        if m:
            k = _resolve_block_key(m.group(1), blocks)
            if k is None:
                out.append(line)
            else:
                out.append(_output_block(k, block_names[k], blocks[k], True, False, download.get(k)))
            continue
        m = re.search(r"\\insertsmalllitcode\{(.*)\}", line)
        if m:
            k = _resolve_block_key(m.group(1), blocks)
            if k is None:
                out.append(line)
            else:
                out.append(_output_block(k, block_names[k], blocks[k], True, True, download.get(k)))
            continue
        out.append(line)

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text("".join(out), encoding="utf-8")
    return sorted(download.values())


def process_many(chapters: list[str], year: str) -> list[str]:
    generated_cpp: list[str] = []
    for ch in chapters:
        dst = GEN_TEX / f"{ch}.tex"
        src = chapter_source(ch)
        if src.name.endswith(".tex.in"):
            generated_cpp.extend(process_literate_file(src, dst, year=year, emit_cpp=True))
        else:
            dst.write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    return sorted(set(generated_cpp))
