SEND+MORE=MONEY
trace::post(s:posted(1))
trace::post(s:subsumed)
  ...
trace::propagate(id:2,s:fix)
  ...
trace::commit(id:1)
        var[1] = 4
trace::propagate(id:2,s:subsumed)
  ...
trace::propagate(id:1,s:failed)
  ...
